### ISSUE TITLE
is ocaml-opus based on the latest opus release?

### ISSUE THREAD

**Issue by wizbox** [savonet/ocaml-opus#3]
The latest opus releases are (as time of this post) :
opus-1.2.tar.gz
opus-tools-0.1.9.tar.gz

Is ocaml-opus based on the latest versions of opus to make sure its using best possible sound quality?

**Comment by toots** [comment]
Hi,

The bindings uses whatever version is installed on your system. It should compile just fine with the latest release library.

What OS are you using? How do you install the C library?

**Comment by wizbox** [comment]
Slackware. I install liquidsoap from source using the liquidsoap-x.x.x-full.tar.bz2 release. I didn't realise liquidsoap bindings use libs what are installed on the system, good news :)

**Comment by toots** [comment]
Cool. Closing then!
